CREATE TABLE "ELDERLY" (
  "ID" integer GENERATED AS IDENTITY PRIMARY KEY,
  "NAME" integer NOT NULL,
  "AGE" integer DEFAULT 0,
  "CONTACT" varchar2,
  "CREATE_TIME" timestamp NOT NULL
);

CREATE TABLE "ROBOT_MENUAL" (
  "ID" integer PRIMARY KEY,
  "RANK" varchar2,
  "DETECT_METHOD" varchar2,
  "AGE" integer DEFAULT 0,
  "TOTAL_ATTEMPTS" integer,
  "SUCCESS_ATTEMPTS" timestamp,
  "CREATE_TIME" timestamp NOT NULL
);

CREATE TABLE "ROBOT_DETECT" (
  "NO" integer GENERATED AS IDENTITY,
  "ID" integer,
  "CREATE_TIME" timestamp NOT NULL,
  "TEXT" varchar2,
  "EMOTION" varchar2 DEFAULT 'y',
  "DETECT_METHOD" varchar2,
  "SUCCESS_YN" varchar2 DEFAULT 'y',
  PRIMARY KEY ("NO", "ID")
);

CREATE TABLE "ROBOT_DIALOG" (
  "ID" integer PRIMARY KEY,
  "CREATE_TIME" timestamp NOT NULL,
  "ELDERLY_TEXT" varchar2,
  "ROBOT_TEXT" varchar2,
  "MORNING_NIGHT" varchar2 DEFAULT 'morning'
);

CREATE TABLE "CARE_HANDOVER" (
  "ID" integer PRIMARY KEY,
  "CREATE_TIME" timestamp NOT NULL,
  "TEXT" varchar2
);

ALTER TABLE "ELDERLY" ADD FOREIGN KEY ("ID") REFERENCES "ROBOT_MENUAL" ("ID");

ALTER TABLE "ELDERLY" ADD FOREIGN KEY ("ID") REFERENCES "ROBOT_DETECT" ("ID");

ALTER TABLE "ELDERLY" ADD FOREIGN KEY ("ID") REFERENCES "ROBOT_DIALOG" ("ID");

ALTER TABLE "ELDERLY" ADD FOREIGN KEY ("ID") REFERENCES "CARE_HANDOVER" ("ID");

ALTER TABLE "ROBOT_DETECT" ADD FOREIGN KEY ("DETECT_METHOD") REFERENCES "ROBOT_MENUAL" ("DETECT_METHOD");
